# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

- template: build-pipeline-Variables.yml            # name of template file to include

steps:
- template: build-pipeline-BuildSteps.yml           # reference to template
- template: build-pipeline-TestSteps.yml            # reference to template
- template: build-pipeline-DeploySteps.yml          # reference to template
